export const initialState = {
  items: [
    {
      meetingName: 'Some name',
      length: 5004,
      nrOfParticipants: 5,
      score: 65,
      date: 1995967409674,
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
      meetingName: 'Some name',
      length: 7004,
      nrOfParticipants: 5,
      score: 65,
      date: 16596409674,
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
      meetingName: 'Some name',
      length: 2004,
      nrOfParticipants: 5,
      score: 65,
      date: 969659609674,
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
      meetingName: 'Some name stupidly long name name name name name name ',
      length: 2004,
      nrOfParticipants: 5,
      score: 65,
      date: 996659609674,
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
      meetingName: 'Some name with special charãcters',
      length: 5526,
      nrOfParticipants: 5,
      score: 65,
      date: 9696659609674,
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
    {
      meetingName: 'Some really really long name',
      length: 2004,
      nrOfParticipants: 5,
      score: 65,
      date: 9561659609674,
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    },
  ],
};
